name: "Apollo Proxy"
description: "Efficient proxy client"
version: "1.2.1"

slug: "apollo_proxy"
url: https://github.com/KubakDev/apollo_proxy_client
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386

host_network: true

options:
  server: ""
  token: ""
  clientname: ""
  user: ""
  email: ""
  certmagic: ""

schema:
  server: str
  token: str
  clientname: str
  user: str
  email: str
  certmagic: str


