name: "Apollo Proxy"
description: "Efficient proxy client"
version: "1.2.5.9.2"

slug: "apollo_proxy"
url: https://github.com/KubakDev/apollo_addons/tree/main/apollo_proxy
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386

map:
  - homeassistant_config
host_network: true

options:
  server: ""
  token: ""
  clientname: ""
  user: ""
  email: ""
  certmagic: ""

schema:
  server: str
  token: str
  clientname: str
  user: str
  email: str
  certmagic: str


