name: "Apollo Proxy"
description: "Efficient proxy client"
version: "1.1.1"
slug: "apollo_proxy"
url: https://github.com/KubakDev/apollo_proxy_client
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386


options:
  server: "admin.tunl.kubakgroup.com"
  token: "yPAca1Vh51e1TbZjqvfTv8lbkiK3avsw"
  clientname: "apollo"
  user: "admin"
  email: "meernahro11@gmail.com"
  certmagic: "/data/certmagic"

schema:
  server: str
  token: str
  clientname: str
  user: str
  email: str
  certmagic: str


