# # https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Apollo Admin
version: "1.0.4"
slug: apolloadmin
description: Connection to Kubak Server
url: "https://github.com/home-assistant/addons-example/tree/main/example"
host_network: true
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
# options:
#   message: "Hello world..."
# schema:
#   message: "str?"
