#!/bin/bash

# Array of error strings
declare -a error_strings=("unable to register tcp forward" "eof" "connection reset by peer" "connection refused" "server misbehaving")

while IFS= read -r line; do
  echo "$line"  # Log line for s6-log or other mechanisms
  lowercase_line=$(echo "$line" | tr '[:upper:]' '[:lower:]')

  for error in "${error_strings[@]}"; do
    if [[ "$lowercase_line" == *"$error"* ]]; then
      echo "Detected critical error, exiting..."
    #   echo "${257}" > /run/s6-linux-init-container-results/exitcode
    #   exec /run/s6/basedir/bin/halt
      exit 256
    fi
  done
done
