#!/bin/bash
# Generic finish script that decides what to do when the service exits.

if [ "${1}" -ne 0 ]; then  # If exit code not zero, it failed
  # Log it
  echo "Service crashed with exit code ${1}. Restarting..." >&2
  # Optional: Perform any needed cleanup here
  echo "${APP_EXIT_CODE}" > /run/s6-linux-init-container-results/exitcode
  exec /run/s6/basedir/bin/halt

  # Prevent restart loop by waiting a bit
  sleep 1
else
  echo "Service exited normally with code ${1}. Not restarting." >&2
fi

# Exit with 0 to cleanly finish without restarting the service
exit 0


#!/usr/bin/env bashio
# ==============================================================================
# Take down the S6 supervision tree when example fails
# s6-overlay docs: https://github.com/just-containers/s6-overlay
# ==============================================================================

# declare APP_EXIT_CODE=${1}

# if [[ "${APP_EXIT_CODE}" -ne 0 ]] && [[ "${APP_EXIT_CODE}" -ne 256 ]]; then
  
#   bashio::log.warning "Halt add-on with exit code ${APP_EXIT_CODE}"
#   echo "${APP_EXIT_CODE}" > /run/s6-linux-init-container-results/exitcode
#   exec /run/s6/basedir/bin/halt
# fi

# bashio::log.info "Service restart after closing"